// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SlackTube.Api.Data;

#nullable disable

namespace SlackTube.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602135511_AddSlackWorkspaces")]
    partial class AddSlackWorkspaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SlackTube.Api.Domain.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ListeningChannelId")
                        .HasColumnType("text");

                    b.Property<string>("SlackBotTokenEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("SlackSigningSecretEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("StatusMessageTs")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("SlackTube.Api.Domain.GoogleToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountEmail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("google_tokens", (string)null);
                });

            modelBuilder.Entity("SlackTube.Api.Domain.JobStateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("job_state_history", (string)null);
                });

            modelBuilder.Entity("SlackTube.Api.Domain.SlackChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMember")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlackChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SlackChannelId");

                    b.HasIndex("WorkspaceId", "SlackChannelId")
                        .IsUnique();

                    b.ToTable("slack_channels", (string)null);
                });

            modelBuilder.Entity("SlackTube.Api.Domain.SlackWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthedUserId")
                        .HasColumnType("text");

                    b.Property<string>("BotTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BotUserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<string>("SlackTeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SlackTeamId")
                        .IsUnique();

                    b.ToTable("slack_workspaces", (string)null);
                });

            modelBuilder.Entity("SlackTube.Api.Domain.UploadJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BytesTotal")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesTransferred")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DriveFileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<int>("QuotaUnitsCharged")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresConfirmation")
                        .HasColumnType("boolean");

                    b.Property<string>("SlackChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlackEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlackMessageTs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlackUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YouTubeUrl")
                        .HasColumnType("text");

                    b.Property<string>("YouTubeVideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SlackEventId");

                    b.HasIndex("State");

                    b.ToTable("upload_jobs", (string)null);
                });

            modelBuilder.Entity("SlackTube.Api.Domain.JobStateHistory", b =>
                {
                    b.HasOne("SlackTube.Api.Domain.UploadJob", "Job")
                        .WithMany("History")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SlackTube.Api.Domain.SlackChannel", b =>
                {
                    b.HasOne("SlackTube.Api.Domain.SlackWorkspace", "Workspace")
                        .WithMany("Channels")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("SlackTube.Api.Domain.SlackWorkspace", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("SlackTube.Api.Domain.UploadJob", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
